[book]
authors = ["Junwang Zhao"]
language = "en"
multilingual = false
src = "src"
title = "Postgres Weekly, A Hackerâ€™s Digest"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/pgweekly/pgweekly"

[output.html.fold]
enable = true     # whether or not to enable section folding
level = 2         # the depth to start folding
